- name: Création d'un poste virtuel pour les tests
  hosts: localhost
  connection: local

  tasks:


    - name: Start the container
      command: 'docker run -d --name {{VIRTUAL_GUEST_CONTAINER_NAME}} --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro  -v /var/run/docker.sock:/var/run/docker.sock --expose 22 {{VIRTUAL_GUEST_IMAGE_NAME}}'
      become: true

    - name: Create the user
      command: 'docker exec -t {{VIRTUAL_GUEST_CONTAINER_NAME}} /dockerstartup/createUser.sh {{ GUEST_USERNAME }} {{ GUEST_PASSWORD }}'
      become: true